### PR TITLE
Fix content overflow scenarios in modal

### PR DESCRIPTION
**Pull request by Kushagra8888**
* Fixes the overflow behavior in the cases of modals with panels and adds a few stories for the same.
* Applies the `max-height` property on the modal. Earlier it was incorrectly set  as height instead of max-height.
* Not adding a new prop for `height` for now, it can still be controlled externally using css if required.

### CODE REVIEW

**Comment by arorayash** [comment]
Everything looks good, just one thing - if the body has custom padding, so should the footer. Can we have that? @Kushagra8888

**Comment by Kushagra8888** [comment]
@arorayash makes sense, for that matter should the heading also be open to be customized? Also, since we might move to the new API, we could also explore the option of not having a padding prop at all, and letting the user individually override the styles using css. I would be in favor of the latter, what are your thoughts?

**Comment by arorayash** [comment]
Yeah agree that with the new api, padding as a prop doesn’t make much
sense.
But there should be some default padding. Could be overridden by the
inherent css prop of styled components?

**Comment by Kushagra8888** [comment]
@arorayash Yes we can ensure that in the new implementation that they can be overrriden using the `css` prop of styled components.

**Comment by arorayash** [comment]
@Kushagra8888 Perfect then, let's do that.

**Pull request merged**
